### ISSUE TITLE
gears_create_shader_from_file: open: shaders/gears.vsh: No such file or directory

### ISSUE THREAD

**Issue by benner** [michaeljclark/glkitty#4]
Interesting project!

I wanted to try. I've build it and run and got:

```
% ./build/kitty_gears -s 512x512
gears_create_shader_from_file: open: shaders/gears.vsh: No such file or directory
```

**Comment by mwaitzman** [comment]
Simply running
```zsh
cp shaders/gears{.v150,}.vsh
cp shaders/gears{.v150,}.fsh
```
in the root of the repo seems to work for me. Actually the v120 versions work for me as well, even mixing the two (e.g. `cp shaders/gears.v120.vsh shaders/gears.vsh; cp shaders/gears.v150.fsh shaders/gears.fsh; ./build/kitty_gears -x -z`)

**Comment by benner** [comment]
It worked for me too

**Comment by larkmjc** [comment]
oh thanks. I must have copies of the shaders that were not committed. this changed when I added multiple shader versions.
